---
- hosts: test
  become: true
  tasks:
  - name: create container
    community.docker.docker_container:
      name: web_page
      image: miltonvilleda/pagina_img:lts
      state: started
      ports:
      - "8081:80"
      restart_policy: always