---
- name: production-server
  hosts: production
  become: true
  tasks:
  - name: remove container
    docker_container:
      name: web_page_prod
      state: absent
  - name: create container
    docker_container:
      name: web_page_prod
      image: miltonvilleda/pagina_img:lts
      state: present
      ports:
      - "8082:80"
      restart_policy: always