---
- name: production-server
  hosts: production
  become: true
  tasks:
  - name: Realizar pull de imagenes
    shell: sudo docker pull miltonvilleda/pagina_img:latest
  - name: remove container
    docker_container:
      name: web_page_prod
      state: absent
  - name: create container
    docker_container:
      name: web_page_prod
      image: miltonvilleda/pagina_img:latest
      state: started
      ports:
      - "8082:80"
      restart_policy: always