---
- hosts: test
  become: true
  tasks:
  - name: create container
    docker_container:
      name: web_page
      image: miltonvilleda/pagina_img:lts
      state: started
      ports:
      - "8081:80"
    vars:
      ansible_python_interpreter: /bin/python3