---
- name: test-server
  hosts: test
  become: true
  tasks:
  - name: stop container
    docker_container:
      name: web_page
      state: stopped
  - name: remove container
    docker_container:
      name: web_page
      state: absent
  - name: create container
    docker_container:
      name: web_page
      image: miltonvilleda/pagina_img:lts
      state: present
      ports:
      - "8081:80"
      restart_policy: always
